name: polymerize
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://github.com/dam0vm3nt/devc_builder
description: An experimental Polymer 2 support with DDC
version: 0.4.1
environment:
   sdk: ">=1.8.0 <2.0.0"

dependencies:
 dev_compiler:
  hosted:
   name: dev_compiler
   url: "http://pub.drafintech.it:5001"
  version: 0.2.0-unofficial.2016111201
#  path: ../sdk/pkg/dev_compiler
#  git:
#   url: https://github.com/dart-lang/dev_compiler
 analyzer: any
 args: any
 stack_trace: any
 resource: any
 homedir: any
 glob: ^1.1.3
# pub_cache: any
# pub_client: any
 archive: any
 package_resolver: any
# dartson: '0.2.6'
# build:
#  git:
#   url: https://github.com/dart-lang/build.git
executables:
 polymerize: polymerize
#dependency_overrides:
# analyzer: 0.29.1
# dev_compiler:
#  path: ../sdk/pkg/dev_compiler
